//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_WindowsApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vehparking-db.documents.azure.com:443/")]
        public string CosmosDbEndpoint {
            get {
                return ((string)(this["CosmosDbEndpoint"]));
            }
            set {
                this["CosmosDbEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15EiHq70QkkSegBSMbEveqb7TxK7lHjDjLgbLMFemqBdgOxV7DYZ6Rjq05oV4G3Y3F8KOgdi8QF5ACDb0" +
            "JY2lA==")]
        public string CosmosDbKey {
            get {
                return ((string)(this["CosmosDbKey"]));
            }
            set {
                this["CosmosDbKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VPMSystem")]
        public string CosmosDbName {
            get {
                return ((string)(this["CosmosDbName"]));
            }
            set {
                this["CosmosDbName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[A-Z]{2}[0-9]{2,3}[A-Z]{1,3}[0-9]{1,4}")]
        public string VehicleNumberPattern1 {
            get {
                return ((string)(this["VehicleNumberPattern1"]));
            }
            set {
                this["VehicleNumberPattern1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VehicleNumberPattern2 {
            get {
                return ((string)(this["VehicleNumberPattern2"]));
            }
            set {
                this["VehicleNumberPattern2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VehicleNumberPattern3 {
            get {
                return ((string)(this["VehicleNumberPattern3"]));
            }
            set {
                this["VehicleNumberPattern3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IN")]
        public string GateMode {
            get {
                return ((string)(this["GateMode"]));
            }
            set {
                this["GateMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GateNumber {
            get {
                return ((int)(this["GateNumber"]));
            }
            set {
                this["GateNumber"] = value;
            }
        }
    }
}
